### ISSUE TITLE
aVQuery.limit(1)   runtime error

### ISSUE THREAD

**Issue by nne998** [LunaGao/leancloud_flutter_plugin#10]
hi,

my example:
```dart
 AVQuery avQuery = new AVQuery("Demo");
    avQuery.whereEqualTo("name", "aaa");
    avQuery.orderByDescending("date");
    avQuery.limit(1);
```

will cus a runtime error:
```
Exception has occurred.
_TypeError (type 'int' is not a subtype of type 'String')
```

in: leancloud_flutter_plugin-0.0.3/lib/leancloud_query.dart
```dart
 /// set query result limit count
  AVQuery limit(int limit) {
    _setQueriesValue("limit", limit, null);
    return this;
  }
```

Maybe It should change the  "limit---->  limit.toString()"

**Comment by LunaGao** [comment]
Thank you for report this issue. I will check it.

**Comment by LunaGao** [comment]
will fixed in 0.0.4 version

**Comment by zoumiaojiang** [comment]
+1 same problem,

https://github.com/LunaGao/leancloud_flutter_plugin/blob/master/lib/leancloud_query.dart#L133
```dart
 var queryClass = <dynamic, dynamic>{};
```
it's work like this

**Comment by LunaGao** [comment]
> +1 same problem,
> 
> https://github.com/LunaGao/leancloud_flutter_plugin/blob/master/lib/leancloud_query.dart#L133
> 
> ```dart
>  var queryClass = <dynamic, dynamic>{};
> ```
> 
> it's work like this

Yeah, I think this is a greater solution than using toString function. I will using this solution in v0.0.5 version.
