### ISSUE TITLE
Exception when use cql query

### ISSUE THREAD

**Issue by zoumiaojiang** [LunaGao/leancloud_flutter_plugin#13]
**Describe the bug**

![image](https://user-images.githubusercontent.com/3365978/59841926-f9a94980-9387-11e9-949a-d1d4dbaca0d6.png)

my code:

```dart
    var cql = "select * from TestTable where num > 1000";
    AVQuery.doCloudQuery(cql).then((objects) {
      print(objects);
      print("Queryed!");
    });
```

**Comment by LunaGao** [comment]
So sorry cql function is in future.
It will be added in v0.0.5 version.

**Comment by LunaGao** [comment]
fixed in https://github.com/LunaGao/leancloud_flutter_plugin/commit/f51e937113b26c43bc3beccc3806bef6368feb39
