### ISSUE TITLE
Why Querying All Data only returns 100 entries?

### ISSUE THREAD

**Issue by ZYHZ100** [LunaGao/leancloud_flutter_plugin#16]
I use this function to query data from leancloud. In the leancloud, the class I query has about 6600 entries, and I want to get them all, but when I use this function I only get 100 entries. Please help me if you have any idea. Thank you so much!!!

Future<bool> _queryAllWords(String BookName) async{
    AVQuery avQuery = new AVQuery(ObjectName);
    lists=new List<Word>();
//    avQuery.whereGreaterThanOrEqualTo("Id", 1);
    //avQuery.whereLessThanOrEqualTo("Id", "6566");
    //avQuery.limit("1000");
    await avQuery.find().then((objects) {
      i=0;
      objects.forEach((item) {
        lists.add(new Word(item.get("Spanish"),item.get("Type"),item.get("Chinese")));
        i++;
      });

      return true;
    });
    return false;
  }

**Comment by ZYHZ100** [comment]
I achieve my goal by call this avQuery.find().then several times by set "whereGreaterThanOrEqualTo" and "whereLessThanOrEqualTo" but I need to use 
var queryClass = <dynamic, dynamic>{};
, the soution mentioned in another closed issue. Thanks for that!!

**Comment by LunaGao** [comment]
According Leancloud document: https://leancloud.cn/docs/leanstorage_guide-objc.html#hash827605266
`可以通过指定 limit 限制返回结果的数量（默认为 100）：`
`由于性能原因，limit 最大只能设为 1000。即使将其设为大于 1000 的数，云端也只会返回 1,000 条结果。`
It looks like 1000 entries returned is the max value and default value is 100. 
So you need to set limit value by yourself. 

And about your other question, please create another issue or add a comment in #10 .
